/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateCustomerDiscoveryModelInput = {
  email: string,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
  role?: string | null,
  city: string,
  state?: string | null,
  monthlyLossFromTheft?: string | null,
  merchandiseTheftCategories?: Array< string | null > | null,
  monthlySecuritySpend?: string | null,
  securityImprovements?: string | null,
  roleChallenges?: string | null,
  expensiveTheftTypes?: Array< string | null > | null,
  theftPreventionTools?: Array< string | null > | null,
  theftPreventionEffectiveness?: string | null,
  theftPatterns?: string | null,
  staffTraining?: string | null,
  strategyReviewFrequency?: string | null,
  incidentHandling?: string | null,
  theftImpact?: string | null,
  additionalSupport?: string | null,
  collaborationsWithLawEnforcement?: string | null,
  balanceSecurityWithExperience?: string | null,
  faceRecognitionEnhancement?: string | null,
};

export type CustomerDiscoveryModel = {
  __typename: "CustomerDiscoveryModel",
  email: string,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
  role?: string | null,
  city?: string | null,
  state?: string | null,
  monthlyLossFromTheft?: string | null,
  merchandiseTheftCategories?: Array< string | null > | null,
  monthlySecuritySpend?: string | null,
  securityImprovements?: string | null,
  roleChallenges?: string | null,
  expensiveTheftTypes?: Array< string | null > | null,
  theftPreventionTools?: Array< string | null > | null,
  theftPreventionEffectiveness?: string | null,
  theftPatterns?: string | null,
  staffTraining?: string | null,
  strategyReviewFrequency?: string | null,
  incidentHandling?: string | null,
  theftImpact?: string | null,
  additionalSupport?: string | null,
  collaborationsWithLawEnforcement?: string | null,
  balanceSecurityWithExperience?: string | null,
  faceRecognitionEnhancement?: string | null,
};

export type UpdateCustomerDiscoveryModelInput = {
  email: string,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
  role?: string | null,
  city: string,
  state?: string | null,
  monthlyLossFromTheft?: string | null,
  merchandiseTheftCategories?: Array< string | null > | null,
  monthlySecuritySpend?: string | null,
  securityImprovements?: string | null,
  roleChallenges?: string | null,
  expensiveTheftTypes?: Array< string | null > | null,
  theftPreventionTools?: Array< string | null > | null,
  theftPreventionEffectiveness?: string | null,
  theftPatterns?: string | null,
  staffTraining?: string | null,
  strategyReviewFrequency?: string | null,
  incidentHandling?: string | null,
  theftImpact?: string | null,
  additionalSupport?: string | null,
  collaborationsWithLawEnforcement?: string | null,
  balanceSecurityWithExperience?: string | null,
  faceRecognitionEnhancement?: string | null,
};

export type DeleteCustomerDiscoveryModelInput = {
  email: string,
  city: string,
};

export type TableCustomerDiscoveryModelFilterInput = {
  email?: TableStringFilterInput | null,
  additionalFeedback?: TableStringFilterInput | null,
  theftPreventionPlans?: TableStringFilterInput | null,
  balance?: TableStringFilterInput | null,
  storeName?: TableStringFilterInput | null,
  role?: TableStringFilterInput | null,
  city?: TableStringFilterInput | null,
  state?: TableStringFilterInput | null,
  monthlyLossFromTheft?: TableStringFilterInput | null,
  merchandiseTheftCategories?: TableStringFilterInput | null,
  monthlySecuritySpend?: TableStringFilterInput | null,
  securityImprovements?: TableStringFilterInput | null,
  roleChallenges?: TableStringFilterInput | null,
  expensiveTheftTypes?: TableStringFilterInput | null,
  theftPreventionTools?: TableStringFilterInput | null,
  theftPreventionEffectiveness?: TableStringFilterInput | null,
  theftPatterns?: TableStringFilterInput | null,
  staffTraining?: TableStringFilterInput | null,
  strategyReviewFrequency?: TableStringFilterInput | null,
  incidentHandling?: TableStringFilterInput | null,
  theftImpact?: TableStringFilterInput | null,
  additionalSupport?: TableStringFilterInput | null,
  collaborationsWithLawEnforcement?: TableStringFilterInput | null,
  balanceSecurityWithExperience?: TableStringFilterInput | null,
  faceRecognitionEnhancement?: TableStringFilterInput | null,
};

export type TableStringFilterInput = {
  ne?: string | null,
  eq?: string | null,
  le?: string | null,
  lt?: string | null,
  ge?: string | null,
  gt?: string | null,
  contains?: string | null,
  notContains?: string | null,
  between?: Array< string | null > | null,
  beginsWith?: string | null,
  attributeExists?: boolean | null,
  size?: ModelSizeInput | null,
};

export type ModelSizeInput = {
  ne?: number | null,
  eq?: number | null,
  le?: number | null,
  lt?: number | null,
  ge?: number | null,
  gt?: number | null,
  between?: Array< number | null > | null,
};

export type CustomerDiscoveryModelConnection = {
  __typename: "CustomerDiscoveryModelConnection",
  items?:  Array<CustomerDiscoveryModel | null > | null,
  nextToken?: string | null,
};

export type CreateCustomerDiscoveryModelMutationVariables = {
  input: CreateCustomerDiscoveryModelInput,
};

export type CreateCustomerDiscoveryModelMutation = {
  createCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type UpdateCustomerDiscoveryModelMutationVariables = {
  input: UpdateCustomerDiscoveryModelInput,
};

export type UpdateCustomerDiscoveryModelMutation = {
  updateCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type DeleteCustomerDiscoveryModelMutationVariables = {
  input: DeleteCustomerDiscoveryModelInput,
};

export type DeleteCustomerDiscoveryModelMutation = {
  deleteCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type GetCustomerDiscoveryModelQueryVariables = {
  email: string,
  city: string,
};

export type GetCustomerDiscoveryModelQuery = {
  getCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type ListCustomerDiscoveryModelsQueryVariables = {
  filter?: TableCustomerDiscoveryModelFilterInput | null,
  limit?: number | null,
  nextToken?: string | null,
};

export type ListCustomerDiscoveryModelsQuery = {
  listCustomerDiscoveryModels?:  {
    __typename: "CustomerDiscoveryModelConnection",
    items?:  Array< {
      __typename: "CustomerDiscoveryModel",
      email: string,
      additionalFeedback?: string | null,
      theftPreventionPlans?: Array< string | null > | null,
      balance?: string | null,
      storeName?: string | null,
      role?: string | null,
      city?: string | null,
      state?: string | null,
      monthlyLossFromTheft?: string | null,
      merchandiseTheftCategories?: Array< string | null > | null,
      monthlySecuritySpend?: string | null,
      securityImprovements?: string | null,
      roleChallenges?: string | null,
      expensiveTheftTypes?: Array< string | null > | null,
      theftPreventionTools?: Array< string | null > | null,
      theftPreventionEffectiveness?: string | null,
      theftPatterns?: string | null,
      staffTraining?: string | null,
      strategyReviewFrequency?: string | null,
      incidentHandling?: string | null,
      theftImpact?: string | null,
      additionalSupport?: string | null,
      collaborationsWithLawEnforcement?: string | null,
      balanceSecurityWithExperience?: string | null,
      faceRecognitionEnhancement?: string | null,
    } | null > | null,
    nextToken?: string | null,
  } | null,
};

export type OnCreateCustomerDiscoveryModelSubscriptionVariables = {
  email?: string | null,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
};

export type OnCreateCustomerDiscoveryModelSubscription = {
  onCreateCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type OnUpdateCustomerDiscoveryModelSubscriptionVariables = {
  email?: string | null,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
};

export type OnUpdateCustomerDiscoveryModelSubscription = {
  onUpdateCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};

export type OnDeleteCustomerDiscoveryModelSubscriptionVariables = {
  email?: string | null,
  additionalFeedback?: string | null,
  theftPreventionPlans?: Array< string | null > | null,
  balance?: string | null,
  storeName?: string | null,
};

export type OnDeleteCustomerDiscoveryModelSubscription = {
  onDeleteCustomerDiscoveryModel?:  {
    __typename: "CustomerDiscoveryModel",
    email: string,
    additionalFeedback?: string | null,
    theftPreventionPlans?: Array< string | null > | null,
    balance?: string | null,
    storeName?: string | null,
    role?: string | null,
    city?: string | null,
    state?: string | null,
    monthlyLossFromTheft?: string | null,
    merchandiseTheftCategories?: Array< string | null > | null,
    monthlySecuritySpend?: string | null,
    securityImprovements?: string | null,
    roleChallenges?: string | null,
    expensiveTheftTypes?: Array< string | null > | null,
    theftPreventionTools?: Array< string | null > | null,
    theftPreventionEffectiveness?: string | null,
    theftPatterns?: string | null,
    staffTraining?: string | null,
    strategyReviewFrequency?: string | null,
    incidentHandling?: string | null,
    theftImpact?: string | null,
    additionalSupport?: string | null,
    collaborationsWithLawEnforcement?: string | null,
    balanceSecurityWithExperience?: string | null,
    faceRecognitionEnhancement?: string | null,
  } | null,
};
