// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
  API: {
      GraphQL: {
        endpoint: 'https://fm5ocqeqzzgczjn5x4semdibui.appsync-api.us-east-1.amazonaws.com/graphql',
        region: 'us-east-1',
        defaultAuthMode: 'apiKey',
        apiKey: 'da2-s5j6wqqeobgsxd7ajjaioyraqy'
      }
  }
};

export default config;